### ISSUE TITLE
"composer install" not working.

### ISSUE THREAD

**Issue by flynncupitt** [mikealmond/hq-trivia-assistant#1]
Hi, I'm attempting to install this on a virtual machine running kali linux and all the commands have worked so far, except this one. I was wondering if there was something I'm doing wrong, or if there is a way around it. I checked the file, and there is only a "composer.json" file. Do i run that one?

**Comment by mikealmond** [comment]
You'll need to install composer from https://getcomposer.org/doc/00-intro.md#globally.
