### ISSUE TITLE
Couple things

### ISSUE THREAD

**Issue by pazon12** [mikealmond/hq-trivia-assistant#10]
One: How do I get my bearer ID on Android 7 w/o root.
Two: I get this error, if it's bearer ID related then nevermind
`Connected.
PHP Notice:  Undefined index: type in C:\Users\XX\hq-trivia-assistant\run.php on line 81
PHP Notice:  Undefined index: type in C:\Users\XX\hq-trivia-assistant\run.php on line 87
Reconnecting...
`

**Comment by pazon12** [comment]
Ah. Issue. I do that, but then all the packets from HQ have no data, plus HQ does not connect to the internet correctly. I've also tried charles, but it has issues with certificates. I believe its an issue with Android 7+ due to certificates not being trusted unless the no data issue is something on my end. I also don't have the ability to root the phone atm.

**Comment by ifvictr** [comment]
I also ran into the problem of empty packets, but resolved the issue by
making sure I had installed the certificates properly.

**Comment by pazon12** [comment]
Android version? Also what did you do to ensure that?
