### ISSUE TITLE
Fatal error before Method 2 returned answers on Q1

### ISSUE THREAD

**Issue by MattH33** [mikealmond/hq-trivia-assistant#101]
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Any idea what caused this? I actually won on the previous game last night, now I'm paranoid they caught me!

**Comment by AdityaGupta1** [comment]
Testing it on the game going on right now, will report if I get a similar error

**Comment by perfectusr** [comment]
haha yep ^ I was just about to update you guys 

no errors on my end, but this game was REALLY tough on the bot. I guess we just got lucky last night lol

**Comment by dsf3449** [comment]
I added Wikipedia as a search option as per PR #85 and it improved the results of some of the answers for tonight's game.  I recommend trying that for at least one game to see if it improves for you as well.

**Comment by AdityaGupta1** [comment]
I'll try it tomorrow, hopefully it will improve results.

**Comment by MattH33** [comment]
Missed the game last night, but all was normal for today's afternoon game. Hopefully it was just a one-off connectivity issue. Thanks for mentioning that Wikipedia option, I'll give it a try.
