### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by jctlc5** [mikealmond/hq-trivia-assistant#12]
having trouble getting token and user id, please explain, would appreciate, thanks!

**Comment by ifvictr** [comment]
@jctlc5 Your user ID is your username. As for the token, you can use a packet capturing tool like [Charles Proxy](https://www.charlesproxy.com/) or [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) (if you're on Android).

**Comment by robertsmith7** [comment]
[https://github.com/mikealmond/hq-trivia-assistant/issues/5](url)
Do some more reading before you ask a question
