### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Codeseys** [mikealmond/hq-trivia-assistant#14]
Well I got the connection working but it looks like method 1 or something doesn't work
How do I fix this???:
Connected.

```
 --------------------------------------



Which of these is NOT a skin care brand?

--------------------------------------------------------
“NOT” DETECTED. USE THE ANSWER THAT IS THE LEAST SUCCESSFUL
--------------------------------------------------------
METHOD 1
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php:189
Stack trace:
#0 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(118): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(67): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 /home/bala/hq-trivia-assistant/functions.php(173): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 /home/bala/hq-trivia-assistant/functions.php(105): handle_responses(Array, Array, 'Which of these ...')
#5 /home/bala/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(203): {closure}(Array)
#6 /home/bala/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promis in /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php on line 189
```

**Comment by portal12** [comment]
hey I received:

PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php:189
Stack trace:
#0 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(118): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(67): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 /root/hq-trivia-assistant/functions.php(173): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 /root/hq-trivia-assistant/functions.php(105): handle_responses(Array, Array, 'What kind of bo...')
#5 /root/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(203): {closure}(Array)
#6 /root/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Array, Array)
 in /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php on line 189

**Comment by topper59** [comment]
sudo apt-get install php7.1-dom
