### ISSUE TITLE
Constantly Connects/Disconnect

### ISSUE THREAD

**Issue by pazon12** [mikealmond/hq-trivia-assistant#15]
Is this normal behavior?
It will Connect, then say reconnecting. Sometimes it's iffy if it will show the answer prompt.

**Comment by mikealmond** [comment]
I never looked into the messages being sent from the app back to the HQ server. Because of this the script doesn't send back the proper pong to HQ's ping. When HQ doesn't detect anything, it closes the connection.

**Comment by pazon12** [comment]
Well because of that, it sometimes doesn't open the answer search because of timing :/

**Comment by cbaucom** [comment]
@mikealmond I'm getting the following issue while trying to run and it just repeats over and over: 


Notice: Undefined index: type in run.php on line 87
Reconnecting...

Connected.
PHP Notice:  Undefined index: type in run.php on line 81

Notice: Undefined index: type in run.php on line 81
PHP Notice:  Undefined index: type in run.php on line 87

**Comment by Aiddog10** [comment]
@mikealmond Is there a way to fix this? Or are you saying the script doesn't work?
