### ISSUE TITLE
No autoload.php

### ISSUE THREAD

**Issue by roseyg71** [mikealmond/hq-trivia-assistant#2]
When I run php run.php I get

`Fatal error: require(): Failed opening required '/Users/gabe/hq-trivia-assistant/vendor/autoload.php' (include_path='.:') in /Users/gabe/hq-trivia-assistant/run.php on line 9
`

**Comment by mikealmond** [comment]
You'll need to run `composer install` before you can run it. This requires that you have Composer installed https://getcomposer.org/doc/00-intro.md#globally

**Comment by roseyg71** [comment]
I get this when I do composer install ... Your requirements could not be resolved to an installable set of packages.

<img width="557" alt="screen shot 2018-01-24 at 2 46 22 pm" src="https://user-images.githubusercontent.com/24533337/35353510-6919a60e-0115-11e8-8998-4c1c50a40a67.png">

**Comment by mikealmond** [comment]
Can you show me the output of `ls -al` on that directory?

**Comment by nkalupahana** [comment]
Try `./composer.phar install` in that directory.

**Comment by roseyg71** [comment]
I just get `./composer.phar: command not found`

**Comment by roseyg71** [comment]
I'm not getting an error that my php version is not new enough so I am going to try to update it.

**Comment by roseyg71** [comment]
I installed php version 7.2.1 however I am still getting this result for `composer install`

<img width="566" alt="screen shot 2018-01-24 at 4 29 17 pm" src="https://user-images.githubusercontent.com/24533337/35358204-d275888a-0123-11e8-9d28-d8158ad5ff26.png">
