### ISSUE TITLE
Issue with installing Composer

### ISSUE THREAD

**Issue by kokirikat** [mikealmond/hq-trivia-assistant#24]
I have this issue when I run 'composer install' in the folder w/ the app: https://imgur.com/a/77ITB

I have updated my Composer to the latest version, so I'm not quite sure what I'm doing wrong here:/

**Comment by kokirikat** [comment]
No .env file is created in the directory -- however, when I do nano .env in termina while in the directory, I'm prompted to enter my token and ID; when I do enter both, and then run the php, this error pops up: https://imgur.com/a/TZJ8X

**Comment by pazon12** [comment]
Update PHP.  This uses PHP 7.3, not 5.6 unfortunately. Install the latest 7.3, install composer there, then run composer.
