### ISSUE TITLE
error after composer install

### ISSUE THREAD

**Issue by tekshteint** [mikealmond/hq-trivia-assistant#35]
once I got composer install to work I got the following error once it finished running:

'(xenial)tom@localhost:~/Downloads/hq-trivia-assistant$ sudo composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
(xenial)tom@localhost:~/Downloads/hq-trivia-assistant$ sudo composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/dom-crawler v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.3 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.2 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.1 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.0 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for symfony/dom-crawler ^4.0 -> satisfiable by symfony/dom-crawler[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4].
`

So then I checked on the other issues and tried to install php7 and got this error:
`(xenial)tom@localhost:~/Downloads/hq-trivia-assistant$ sudo apt-get install php7.1-dom
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.1-dom
E: Couldn't find any package by glob 'php7.1-dom'
E: Couldn't find any package by regex 'php7.1-dom'
`

What should I do?

**Comment by natefanaro** [comment]
The package `php7.1-dom` does not exist because you are on version `7.0.22` (according to the error message from composer.) Try installing `php7.0-dom` or something similar. This command should help you search for the right package name `apt-cache search php*-dom`

**Comment by tekshteint** [comment]
I tried doing `apt-cache search php*-dom`, and that gave me:   `(xenial)tom@localhost:~/Downloads/hq-trivia-assistant$ apt-cache search php*-dom
php7.0-xml - DOM, SimpleXML, WDDX, XML, and XSL module for PHP
`

So I tried to install php7.0-xml, after which I tried to enter `composer install`, which gave me this string: 

`(xenial)tom@localhost:~/Downloads/hq-trivia-assistant$ sudo composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/dom-crawler v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.3 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.2 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.1 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.0 requires php ^7.1.3 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for symfony/dom-crawler ^4.0 -> satisfiable by symfony/dom-crawler[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4].`

**Comment by tekshteint** [comment]
Nevermind- I solved it with some google searches. I first used these series of commands to add a new repository: 'sudo apt-get install -y python-software-properties'
'sudo add-apt-repository -y ppa:ondrej/php'
'sudo apt-get update -y'

Then I used the command 'sudo apt-get install grep php7.1" to download all the php 7.1 as I was wayyy to lazy to go through and find what I needed, then ran 'composer install', and it worked like a charm.
