### ISSUE TITLE
Where is User ID and Bearer Token?

### ISSUE THREAD

**Issue by Aiddog10** [mikealmond/hq-trivia-assistant#5]
I am in Charles Proxy connected to my iPhone, and I see a tab called https://api-quiz.hype.space. I click on it and in the 2 tabs under it, I look at the content, and it is all gibberish like it is encrypted. Am I in the right spot to find the ID and Token? Or do I need to somehow decrypt this? By the way, this wasn't during a live game so that might be the problem *EDIT* Now there is 4 tabs under api-quiz.hype.space. This is a snippet of the "content" in one tab in charles proxy: `ôðé<;¤Nö|Ç
DôÄ["gF@dêKí ¬F4½ FR9)²ftØæAê×ï³¹µîõÍaÕÎ½×(À,À+À$À#À
À	Ì©À0À/À(À'ÀÀÌ¨=<5/ÿapi-quiz.hype.space
3tspdy/3.1spdy/3http/1.1`. Can anyone tell me what this means?? I tried to right click and do Base 64 Decode but Charles said it wasn't valid

**Comment by robertsmith7** [comment]
I have the exact same question, and I spent about 30 minutes studying all 4 sub tabs and got nothing out of it

**Comment by Aiddog10** [comment]
Ok I found out last night how to do this. So to you first have to go into WiFi settings on your iPhone. Click the ‘i’ on the WiFi network your computer is on, and click on HTTP proxy. Then click on manual and type in your computer’s ip and type in 8888 as the port. Then, under the help tab in Charles Proxy, click install certificate on a mobile device. It will tell you to go to a link on your phone, so go to that link and install the certificate. Then go to General → About → Trust Certificate Settings. Then click enable root access for the Charles Proxy Certificate. Now the content will be unencrypted, and you can take the user id. I saw a very long jumble of letters called the Bearer Authentication, so I assumed that was what he meant by bearer token. I copied those down into the .env file and now I will test it today. Best of luck

**Comment by topper59** [comment]
Yes that is correct, and note that Charles proxy will not work on Android 7+ because you have to make a security exception for the apk to be allowed to use a different certificate. On Android 6 and below you can just use the app Packet Capture and it will capture the proper Bearer and user ID. 

With the proper credentials it does work I tested last night. Method 1 and Method 3 showed 0% for all answers though, but Method 2 worked for me decently well.

**Comment by ninjustu** [comment]
So, if I have android 6 I don't need to do the certificate. And if I have an Android 7+ I would need to install the certificate.

**Comment by topper59** [comment]
No, you still have to install the certificate on Android 6, but that's
really easy. On Android 7+ installing the certificate can be done, but it
won't work unless a security exception is made to the apk file itself which
I had trouble doing.

For Android 6 just use Packet Capture from the Play store and it will
install the certificate for you and decrypt the SSL traffic.

**Comment by ninjustu** [comment]
Is there a YT video tutorial?

**Comment by topper59** [comment]
Not that I know of, it's very straightforward though. Install Packet Capture, run it and it will prompt to install the certificate. Then start capturing packets and open up HQ and let it load. Go back to Packet Capture and stop capturing. Open up the packets and find the reply from the HQ servers that have the relevant info.

**Comment by ninjustu** [comment]
I have a Android 7

**Comment by mikealmond** [comment]
Charles has some documentation on how to enable SSL proxying on their website. https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by topper59** [comment]
Unfortunately Charles suffers from the same issues on Android 7+, and still requires a security exception. I tried on 8.1 and it captures the packets but can't decrypt them. Really the best bet is to use an iPhone or an Android device on 6 or below.

There's more info on this here: https://blog.jeroenhd.nl/article/android-7-nougat-and-certificate-authorities
He describes a method around it, but you must be rooted.

**Comment by robertsmith7** [comment]
I'm still getting a mess of random data under the contents tab of one of my substructure sections for https://api-quiz.hype.space. Under notes it says "SSL Proxying enabled for this host" even though I've followed every step correctly. I've dotted my i's and crossed my t's. Whats next? @mikealmond

**Comment by topper59** [comment]
@robertsmith7 Sounds like it can't decrypt the packets, what phone and OS version do you have?

**Comment by cbaucom** [comment]
@topper59 I am getting "SSL Proxying not enabled for this host: enable in Proxy Settings, SSL locations" in Charles app on Mac, even though I have installed and enabled on iPhone 7P running iOS 11.2.2. I have also setup the proxy on iPhone wifi, setup the SSL Proxy in Charles app with IP of iPhone and * for the port. Can't figure out how to get SSL enabled. Can somone please tell me what I am missing here?

**Comment by frankbeirne** [comment]
@cbaucom Make sure the certificate on iPhone is trusted at root level General → About → Trust Certificate Settings. Then in Charles SSL Proxy Setting trust this host - api-quiz.hype.space

**Comment by cbaucom** [comment]
Thanks @frankbeirne, I had the wrong host in the SSL Proxy settings.  Now I have my userId and token but when I run I get the error below. I've omitted my userId. I assume this is because the game is not live? Will check in a few minutes...  

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api-quiz.hype.space/shows/now?type=hq&userId=XXXXXXX` resulted in a `401 Unauthorized` response:
{
  "error": "Auth not valid",
  "errorCode": 105
}

**Comment by BigNacho56** [comment]
@cbaucom mine is saying the same thing

**Comment by robertsmith7** [comment]
> Make sure the certificate on iPhone is trusted at root level General → About → Trust Certificate Settings. Then in Charles SSL Proxy Setting trust this host - api-quiz.hype.space
that is what made the difference for me, and fixed my encryption issues. None of that is based around issues related to mikes program, so just try random things out from what other people say (as I did).

**Comment by ninjustu** [comment]
@topper59 I installed Packet Capture. I found my Bearer code but I don't know where is my userId

**Comment by robertsmith7** [comment]
@ninjustu it should be the title of one of your sub tabs under the http.....

**Comment by frankbeirne** [comment]
@cbaucom @BigNacho56 Have you set your `HQ_BEARER_TOKEN` and `HQ_USER_ID` in the `.env` file? Looks like it's set to XXXXX right now

**Comment by topper59** [comment]
It's in a packet that comes after the bearer, it's like 6 or so digits
IIRC. Mine was in the same group of packets when I used packet capture

**Comment by ninjustu** [comment]
@topper59 GET /ws/XXXXX the "xxxxx" is the user id?

**Comment by topper59** [comment]
@ninjustu I don't have the raw packet anymore, but I confirmed my ID is 7 digits. It definitely said "userID" before the number, and it was near the beginning of the packet.

**Comment by pazon12** [comment]
@topper59 Is this impossible on android 7 w/o root?

**Comment by topper59** [comment]
@pazon12 This is the only way I know of to do it without root, but I'm pretty sure this is for if you are developing an app
https://medium.com/@elye.project/android-nougat-charlesing-ssl-network-efa0951e66de
I'm not sure if you can apply this to a published APK or not, not my area of expertise.

**Comment by pazon12** [comment]
I don't think I can do this with HQ. The only phone I don't sort of have access to is Android 5, HQ doesn't support it I don't think.

**Comment by topper59** [comment]
Yeah, the only other way I can think of is to emulate Android 6 and use the packet capture app within the emulation.

**Comment by pazon12** [comment]
Best way to emulate A6?
Remix OS does not like my PC.

**Comment by topper59** [comment]
I've never emulated it, but the Android Studio/SDK has an emulator and I believe you should be able to grab a 6.0 image and emulate it that way.

**Comment by Aiddog10** [comment]
I do not have an android but you can install the ssl profile from chls.pro/ssl once you are connected to your computer by http proxy (Server is your computer’s ip, and port is 8888). You have to install it then trust it (on iPhone) by going to General → About → Trust Certificate Settings. Idk about android but most times you can’t access stuff like this on iPhone and you can on android, so maybe it’s flipped this time

**Comment by Aiddog10** [comment]
And this website says (https://community.tealiumiq.com/t5/Tealium-for-Android/Setting-up-Charles-to-Proxy-your-Android-Device/ta-p/5121)
that you can download the certificate from Charles, then change the file extension to .cer (from .pem). Then transfer to android device and you can install it

**Comment by Aiddog10** [comment]
Sorry Android guys, but Charles officially doesn't support newer versions. By the way, I am going to close this issue because we found out how to solve the issue. @mikealmond I still haven't figured how to get this to work, now I get a weird error.
