### ISSUE TITLE
cURL error 60: SSL certificate FIXED!

### ISSUE THREAD

**Issue by tombets2424** [mikealmond/hq-trivia-assistant#54]
**so I run git bash and type the necessary lines of code. Then I get to php run.php and this happens...**

```
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL
certificate problem: unable to get local issuer certificate (see http://curl.hax
x.se/libcurl/c/libcurl-errors.html) in C:\Users\user\Desktop\hq-trivia-assistant
-master\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php
:187
Stack trace:
#0 C:\Users\user\Desktop\hq-trivia-assistant-master\hq-trivia-assistant\vendor\g
uzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactor
y::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\user\Desktop\hq-trivia-assistant-master\hq-trivia-assistant\vendor\g
uzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactor
y::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler
\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\user\Desktop\hq-trivia-assistant-master\hq-trivia-assistant\vendor\g
uzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory
::finish(Object(Guzz in C:\Users\user\Desktop\hq-trivia-assistant-master\hq-triv
ia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187 
```

**Now before you all say go to this thread etc... ill give you things I've done:** 
1. php is up to date!
2. I have put the cacert.pem (or cacert.pem.txt) file in C:\wamp64\bin\php\php7.1.9\extras\ssl
3. I tried a bit of code that disables the ssl cerification (Which is risky)

any help would be appreciated :)

**Comment by tombets2424** [comment]
**so if you have done what I have tried and STILL get the same error, do this:**
1. Download the cacert.pem file correctly
2. locate BOTH php.ini files and edit BOTH of them!!!
3. Add these lines to your cert in both php.ini files:
(To find these lines of code press win+F and type curl ,then press enter twice)
```
curl.cainfo="C:/wamp/cacert.pem"
openssl.cafile="C:/wamp/cacert.pem"

```
4. Remember to get rid of the ; infront of each line. (the second line is slightly below the first one.)
5.Restart Wamp services.
6.Go into the hq-trivia file, right click and run gitbash. Then type php run.php
7.If it works it should say when the next game is BUT, you may get errors so be prepared to not use the program today...

**Comment by manofsteel2017** [comment]
there's onlly one php.ini \
one in xwamp 
about the other one?

**Comment by tombets2424** [comment]
If you used xwamp, follow this.
https://www.youtube.com/watch?v=plc7T4HCJSk

Just remember to add both lines in the camera.Pem file.

**Comment by tombets2424** [comment]
your not randomly putting it anywhere right? You have to put them at the right lines. Also remember the path where your cacert.pem file is will be different so you cant copy and paste the lines provided.

**Comment by tombets2424** [comment]
**first line:** ![image](https://user-images.githubusercontent.com/36307300/36076738-401fd588-0f58-11e8-82ec-596c453c0fc0.png)

**Second line:** 
![image](https://user-images.githubusercontent.com/36307300/36076747-674e7d58-0f58-11e8-9b87-f8f0ffc26c62.png)

**Comment by manofsteel2017** [comment]
haah thanks for the pic man 
very helpful. 
i was adding it in random 

but now i got this error 
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL
certificate problem: unable to get local issuer certificate (see http://curl.hax
x.se/libcurl/c/libcurl-errors.html) in C:\composer\hq-trivia-assistant\vendor\gu
zzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\composer\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFact
ory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\
Handler\EasyHandle), Array)
#1 C:\composer\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFact
ory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Hand
ler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handl
er\CurlFactory))
#2 C:\composer\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlHand
ler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\Cu
rlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\Cur
lFactory))
#3 C:\composer\hq-trivia-assistant\vendo in C:\composer\hq-trivia-assistant\vend
or\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by tombets2424** [comment]
hmmm not sure but.... 
1. have you made the .env file and added your ID and BEARER token? the file should be in the hq-tria-assistant-master folder. 
2. is composer installed and up to date? (go into cmd, type composer then type -v)
3.are you using php 7.1 OR higher?
4.are you opening gitbash in the hq-tria-assistant-master folder. 
5. If these are all fine then I'm not sure. sorry. try looking in the error threads and maybe someone has fixed this already.   :)

**Comment by tombets2424** [comment]
here... you should put it in xwamp\php\extras\ssl    (Or find a similar path the ends in "extras\ssl")
[cacert - Copy.zip](https://github.com/mikealmond/hq-trivia-assistant/files/1714707/cacert.-.Copy.zip)

**Comment by manofsteel2017** [comment]
Thanks Tom 
I added the token which starts with this HQ_BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMyNjczMTksInVzZXJuYxxxxxxxxxxxxxxxxxxxxx
it's even longer. does the code needs to be this long 
and yeah  i have php 7.1  and using gitbash to open it 

maybe i need to kill xwamp service but it won't let me

**Comment by tombets2424** [comment]
yes the BEARER TOKEN is really long and you need all of it!!! the ID is I think about 7 numbers. Just restart your PC, it'll be better.

**Comment by manofsteel2017** [comment]
wait 
my user  ID is number ? not user name ? oops lol
might show me what it looks like if you can

**Comment by tombets2424** [comment]
do you have Charles open?

**Comment by tombets2424** [comment]
10*88*7*  (looks like this without the *) EG: 10988989

**Comment by manofsteel2017** [comment]
i used packet capture

**Comment by tombets2424** [comment]
oh I don't know how to use that. I suppose your ID is near the BEARER TOKEN. it should be labelled.

**Comment by manofsteel2017** [comment]
GET /shows/now HTTP/1.1
x-hq-client: Android/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMyNjczMTksInVzZXJuYW1lIjoibWFub2ZzdGVlbDIwMTgiLCJhdmF0YXJVcmwiOiJzMzovL2h5cGVzcGFjZS1xdWl6L2EvZGYvMzI2NzMxOS1lNFFFaW4uanBnIiwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Remix OS Player Build/MMB29K)
Host: api-quiz.hype.space
Connection: Keep-Alive
Accept-Encoding: gzip


HTTP/1.1 200 OK
Date: Sun, 11 Feb 2018 18:53:20 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 341
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, PUT, POST, PATCH, DELETE, OPTIONS, HEAD
X-Server-Env: dev
X-Hostname: hypeapi-3735990-3e1ub
X-Node-Version: 8.9.4
X-Hype-Version: hypeapi-1.0
X-Hype-Namespace: hype-quiz
Vary: Accept-Encoding
X-Response-Time: 0.001s
X-Varnish: 472994822
Age: 0
Via: 1.1 varnish-v4
Accept-Ranges: bytes

nothing about ID though :(

**Comment by tombets2424** [comment]
are there other tabs?? or are there ways to view hex, html, raw etc....??

**Comment by manofsteel2017** [comment]
yeah i can view as HEX

**Comment by tombets2424** [comment]
anything else? you could try other code types. they sometimes reveal different things.

**Comment by manofsteel2017** [comment]
OH i can see as raw as well
will send show you what they look like

**Comment by manofsteel2017** [comment]
47 45 54 20 2f 73 68 6f  77 73 2f 6e 6f 77 20 48  GET /sho ws/now H
54 54 50 2f 31 2e 31 0d  0a 78 2d 68 71 2d 63 6c  TTP/1.1. .x-hq-cl
69 65 6e 74 3a 20 41 6e  64 72 6f 69 64 2f 0d 0a  ient: An droid/..
41 75 74 68 6f 72 69 7a  61 74 69 6f 6e 3a 20 42  Authoriz ation: B
65 61 72 65 72 20 65 79  4a 68 62 47 63 69 4f 69  earer ey JhbGciOi
4a 49 55 7a 49 31 4e 69  49 73 49 6e 52 35 63 43  JIUzI1Ni IsInR5cC
49 36 49 6b 70 58 56 43  4a 39 2e 65 79 4a 31 63  I6IkpXVC J9.eyJ1c
32 56 79 53 57 51 69 4f  6a 4d 79 4e 6a 63 7a 4d  2VySWQiO jMyNjczM
54 6b 73 49 6e 56 7a 5a  58 4a 75 59 57 31 6c 49  TksInVzZ XJuYW1lI
6a 6f 69 62 57 46 75 62  32 5a 7a 64 47 56 6c 62  joibWFub 2ZzdGVlb
44 49 77 4d 54 67 69 4c  43 4a 68 64 6d 46 30 59  DIwMTgiL CJhdmF0Y
58 4a 56 63 6d 77 69 4f  69 4a 7a 4d 7a 6f 76 4c  XJVcmwiO iJzMzovL
32 68 35 63 47 56 7a 63  47 46 6a 5a 53 31 78 64  2h5cGVzc GFjZS1xd
57 6c 36 4c 32 45 76 5a  47 59 76 4d 7a 49 32 4e  Wl6L2EvZ GYvMzI2N
7a 4d 78 4f 53 31 6c 4e  46 46 46 61 57 34 75 61  zMxOS1lN FFFaW4ua
6e 42 6e 49 69 77 69 64  47 39 72 5a 57 34 69 4f  nBnIiwid G9rZW4iO
6d 35 31 62 47 77 73 49  6e 4a 76 62 47 56 7a 49  m51bGwsI nJvbGVzI
6a 70 62 58 53 77 69 59  32 78 70 5a 57 35 30 49  jpbXSwiY 2xpZW50I
6a 6f 69 49 69 77 69 5a  33 56 6c 63 33 52 4a 5a  joiIiwiZ 3Vlc3RJZ
43 49 36 62 6e 56 73 62  43 77 69 61 57 46 30 49  CI6bnVsb CwiaWF0I
6a 6f 78 4e 54 45 33 4e  7a 59 77 4f 44 49 78 4c  joxNTE3N zYwODIxL
43 4a 6c 65 48 41 69 4f  6a 45 31 4d 6a 55 31 4d  CJleHAiO jE1MjU1M
7a 59 34 4d 6a 45 73 49  6d 6c 7a 63 79 49 36 49  zY4MjEsI mlzcyI6I
6d 68 35 63 47 56 78 64  57 6c 36 4c 7a 45 69 66  mh5cGVxd Wl6LzEif
51 2e 4b 51 49 46 31 63  54 35 4e 51 44 72 37 37  Q.KQIF1c T5NQDr77
68 49 30 6f 5a 45 6e 6f  4f 67 50 59 55 46 66 31  hI0oZEno OgPYUFf1
4a 57 68 45 35 45 49 63  4d 32 4d 42 4d 0d 0a 55  JWhE5EIc M2MBM..U
73 65 72 2d 41 67 65 6e  74 3a 20 44 61 6c 76 69  ser-Agen t: Dalvi
6b 2f 32 2e 31 2e 30 20  28 4c 69 6e 75 78 3b 20  k/2.1.0  (Linux; 
55 3b 20 41 6e 64 72 6f  69 64 20 36 2e 30 2e 31  U; Andro id 6.0.1
3b 20 52 65 6d 69 78 20  4f 53 20 50 6c 61 79 65  ; Remix  OS Playe
72 20 42 75 69 6c 64 2f  4d 4d 42 32 39 4b 29 0d  r Build/ MMB29K).
0a 48 6f 73 74 3a 20 61  70 69 2d 71 75 69 7a 2e  .Host: a pi-quiz.
68 79 70 65 2e 73 70 61  63 65 0d 0a 43 6f 6e 6e  hype.spa ce..Conn
65 63 74 69 6f 6e 3a 20  4b 65 65 70 2d 41 6c 69  ection:  Keep-Ali
76 65 0d 0a 41 63 63 65  70 74 2d 45 6e 63 6f 64  ve..Acce pt-Encod
69 6e 67 3a 20 67 7a 69  70 0d 0a 0d 0a           ing: gzi p....

**Comment by manofsteel2017** [comment]
I think we worked on this enough lol

thanks for all the help though i guess i won't be able to find the ID

**Comment by tombets2424** [comment]
try Charles. it works. unless you can find someone that knows how to work this but, good luck!

**Comment by manofsteel2017** [comment]
charles won't work on 7.0 
or latest iphone updates

**Comment by manofsteel2017** [comment]
Hey tom, i bought a 50 dollars phone just for this lmfao 
i still can't get the ID even after i connected to it. 
i got the bear ID but the other ID can't be found :(
mind post a pic  

Thanks

**Comment by tombets2424** [comment]
wow omg! Go to #59 I made a tutorial!

**Comment by WalnutBunny** [comment]
@tombets2424 if your issue is resolved, could you mark the issue as closed to avoid cluttering the open issues page?

**Comment by tombets2424** [comment]
It's a tutorial but, I can just link them to the thread I guess.
