### ISSUE TITLE
Got this error: cURL error 60

### ISSUE THREAD

**Issue by x-mojojojo** [mikealmond/hq-trivia-assistant#55]
`Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.ht
ml) in C:\Users\jackk.DEADSH0T\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\Users\jackk.DEADSH0T\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Han
dler\EasyHandle), Array)
#1 C:\Users\jackk.DEADSH0T\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler
\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\jackk.DEADSH0T\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlH
andler), Obj in C:\Users\jackk.DEADSH0T\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
`

**Comment by tombets2424** [comment]
Look at #54 
*do you have the cacert.pem file?

**Comment by x-mojojojo** [comment]
No, I dont seem to have. it should be here "C:\wamp64\bin\php\php7.1.9\extras\ssl" right? Where can i get the cacert.pem?

**Comment by x-mojojojo** [comment]
i think it should work fine now
[https://i.imgur.com/8LiYaC9.png](url)

**Comment by tombets2424** [comment]
Does it work?

**Comment by x-mojojojo** [comment]
After doing what you told me i tried to run it. It gave me that message "next show on sunday, 11-Feb-2018 21:00:00 EST for $15000." https://github.com/mikealmond/hq-trivia-assistant/issues/url

**Comment by tombets2424** [comment]
YESS!!! It works (hopefully). You have to wait till tonight and run the code when that lady appears. While she is talking it will say connecting...
Reconnecting....
But when a question appears it it should work. If it doesn't answer the question then you might have another problem. But good luck for tonight!

**Comment by tombets2424** [comment]
YESS!!! It works (hopefully). You have to wait till tonight and run the code when that lady appears. While she is talking it will say connecting...
Reconnecting....
But when a question appears it it should work. If it doesn't answer the question then you might have another problem. But good luck for tonight!

**Comment by x-mojojojo** [comment]
Thanks for the help mate...Good luck to you too!

**Comment by x-mojojojo** [comment]
It worked fluently....i failed at question 12 :( (the cricket one). Always Next time. @mikealmond Thank you for this
