### ISSUE TITLE
USER ID can't be found. 

### ISSUE THREAD

**Issue by manofsteel2017** [mikealmond/hq-trivia-assistant#58]
Hello all, 

I found my Bearer code but not the user ID 
is the user ID my trivia user name  ? or something else
I looked everything for "ID" NOTHING SO FAR
If anyone can take a screenshot or tell me the exact thing to look for
greatly appreciate it 

Thanks

**Comment by amberphoenix** [comment]
it's a 7 digits long numbers only string....

i dont have the packets any more but normally is in a different packet than the bearer is.

your username will appear as well on a line below the user id

e.g user id: 1234567

**Comment by manofsteel2017** [comment]
it will say user ID? 
i looked everywhere in all sections.

**Comment by tombets2424** [comment]
Go to #59 and look at my tutorial see if that helps.
