### ISSUE TITLE
TUTORIAL! BEARER and ID

### ISSUE THREAD

**Issue by tombets2424** [mikealmond/hq-trivia-assistant#59]
**First you want to open Charles and set up everything correctly with your phone (IE: go on to Charles and download the certificate on your phone).**

1. On your phone go to HQ trivia... On Charles a bunch of things will appear you want to look for `https://api-quiz.hype.space`. Click it and press users then me.**( You also want to right click on me and enable ssl proxying!!)**
![image](https://user-images.githubusercontent.com/36307300/36143767-ea9e4494-10a3-11e8-9d03-ce96496389e3.png)

2. When on the me tab look at the top of the box on the right and click contents. This should appear:
![image](https://user-images.githubusercontent.com/36307300/36143941-7452c124-10a4-11e8-9ca2-69343a804abb.png)

3. In the top box my BEARER TOKEN is found and in the code below my ID is found. (The BEARER TOKEN is a long string of numbers and letters, you can easily copy by double clicking it. **DO NOT INCLUDE THE WORK BEARER!** The ID is the 8 number code above your actual username.)

**Comment by manofsteel2017** [comment]
Thank you so much Tom
you are a miracle here.

**Comment by tombets2424** [comment]
No problem :)

**Comment by savageduckerino** [comment]
I dont see users and me, only unknown?

**Comment by savageduckerino** [comment]
Oh nvm i fixed it

**Comment by hitnrun30** [comment]
Ok i got it setup, but all i get in charlesproxy is that the client SSL handshake failed
