### ISSUE TITLE
Method 1 and 2 show 0%

### ISSUE THREAD

**Issue by topper59** [mikealmond/hq-trivia-assistant#6]
Methods 1 and 2 don't show any percent for the answers, and Method 1 seems to take a bit of time as well which delays Method 2 and sometimes cuts it close to the time limit. I only tested this with a few questions last night, but Method 2 seemed to work pretty well.

**Comment by mikealmond** [comment]
Unfortunately there are a few types of questions that Google and Yahoo! just can't answer very well. The rankings come from the number of times the answer comes up in the text snippets returned from the different queries the script makes. Sometimes the answer never appears in the snippets.

**Comment by topper59** [comment]
No worries, it's working on the current game!
