### ISSUE TITLE
"Bearer token and user ID" quick question

### ISSUE THREAD

**Issue by eiby1993** [mikealmond/hq-trivia-assistant#60]
Hi,
Does the bearer token is the one appearing on :
structure : https://api-quiz.hype.space/users/me   -  "contents" tab 
:authorization Bearer "421 characters string" ? 
If so, should include the "Bearer" term before my TOKENID into the HQ_BEARER_TOKEN=? 
Also, do i have to type these credentials into the .env or .env.dist file? I've done it to .env.dist file.
Thank you so much.

**Comment by tombets2424** [comment]
Go to #59 you can pictures of the user ID and BEARER TOKEN. (You need the long string without the word bearer at the beginning). Also type them into both the .env file and .env.dist file.
