### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Monogol** [mikealmond/hq-trivia-assistant#62]
![screen shot 2018-02-14 at 20 31 13](https://user-images.githubusercontent.com/36486721/36223012-be01c16c-11cb-11e8-8551-9ff762b9c75b.png)
I get this error when run run.php. any ideas?

**Comment by Monogol** [comment]
Ok so i just simply updated php and thats it. but now i get this
![screen shot 2018-02-14 at 21 08 25](https://user-images.githubusercontent.com/36486721/36223089-fbaca860-11cb-11e8-9033-3924ff390d07.png)

**Comment by tombets2424** [comment]
What are the black lines covering?

Is php up to date. Also does both your .env and .env.dist contain both your BEARER TOKEN and ID? What is on line 9 as that seems to be a problem.

**Comment by tombets2424** [comment]
Oh actually I just noticed in one of the paths it says your using php5, you need at least 7.1+ to run this.

**Comment by Monogol** [comment]
thanks! in run.php the 9th line is empty 
![screen shot 2018-02-18 at 18 46 50](https://user-images.githubusercontent.com/36486721/36354381-220c5c90-14dc-11e8-9fd6-ecbadbf76ae3.png)

.env file contains everything but i don't have .env.dist file

**Comment by Monogol** [comment]
php is up to date but i still get the same error. I covered my computer account name because it's my full name.

**Comment by tombets2424** [comment]
Hmmmmm... same error? Maybe try downloading the .env.dist file again and adding the BEARER TOKEN and ID. Otherwise I'm not too sure.

**Comment by Monogol** [comment]
tried doing everything from start to finish again and still getting the same error. well thanks anyways

**Comment by tombets2424** [comment]
You should probably find a thread with someone that also has Mac or that has gone through a similar problem. Sorry.

**Comment by Monogol** [comment]
ok so i browsed few threads and found out that i don't have a folder named vendor or something like that

**Comment by tombets2424** [comment]
Yeah I have that but, I don't know how I got it. I'm not sure if it's part of the download or it is created when you do php run.php

**Comment by Monogol** [comment]
mabe you can upload that folder here?

**Comment by Monogol** [comment]
cuz now I opened run.php in editor and on 9 line theres this line which I think creates he Vendor folder.  
![screen shot 2018-02-18 at 22 35 57](https://user-images.githubusercontent.com/36486721/36356552-68bc970c-14fc-11e8-91d8-8c600bf7cdb5.png)
and i think thats the problem. Script can't create that folder or something

**Comment by tombets2424** [comment]
Uninstall composer and reinstall it in GitBash using the lines of code on the code page of this thread.

**Comment by tombets2424** [comment]
These ones 
```
$ git clone https://github.com/mikealmond/hq-trivia-assistant .
$ cd hq-trivia-assistant
$ composer install
```

**Comment by Monogol** [comment]
when i type composer install i get an error   [composer: command not found]   git bash is installed.  earlier I used  commands from [https://getcomposer.org/download/](url) to install it and they created composer files in hq trivia folder

**Comment by Monogol** [comment]
googled about installing composer and found out that for command composer install to work you have to remove .phar ending on composer.phar file now everything installed correctly and I have vendor folder

**Comment by Monogol** [comment]
so everything works now. Thanks for the help.
