### ISSUE TITLE
Question about run-time

### ISSUE THREAD

**Issue by eiby1993** [mikealmond/hq-trivia-assistant#65]
Hi, 
I noticed method 2 takes way longer than method1 on my small computer(corei3 4th gen, 4GB RAM, wifi) , and it displays method2 results either 1 second before time's limit or after time limit.
My question is : could a beefier computer(corei7 6th gen), 16GB of RAM and cabled network connection,  reduce the running time of method 2? 
Thanks again for sharing this app and reading this !
Note: I don't know if this app is running parallel programming or serial programming.

**Comment by tombets2424** [comment]
I suppose... I have an i5 core, 16GB RAM and cabled network and I have 4 seconds spare. This includes method 1 and 2. When method 3 runs I get 2-3 seconds.

**Comment by tombets2424** [comment]
I also believe this is running parallel as otherwise the results would probably be displayed after the question or with a second to spare.
