### ISSUE TITLE
composer install failed to open stream: HTTP request failed!

### ISSUE THREAD

**Issue by Creexy** [mikealmond/hq-trivia-assistant#68]
With command composer install it writes this:

[Composer\Downloader\TransportException]
  The "http://packagist.org/p/psr/http-message%24d89048e97fd631404d507d51f16720ca6d039631611584760e3b4e510098acd6.json" file could not be downloaded: failed to open stream: HTTP request failed!

I'm noob in this things, help me pls

**Comment by tombets2424** [comment]
Do you have....
1.Php installed (7.1 or above)
2. GitBash installed
3. Composer installed.
4. xwamp installed.

**Comment by Creexy** [comment]
only don't have xwamp installed

**Comment by tombets2424** [comment]
Try skipping that step and follow the rest of the commands to create the .env file

**Comment by Creexy** [comment]
I already created .env
And the next step gives me this:
$ php run.php
PHP Warning:  require(C:\Users\PHP Fatal error:  require(): Failed opening required 'C:
\Users\

**Comment by Creexy** [comment]
Composer diagnose:

Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprie            tary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A1            4642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50            952
OK
Checking composer version: OK
Composer version: 1.6.3
PHP version: 7.2.2
PHP binary path: C:\Users\▒▒▒▒▒▒\Desktop\php-7.2.2-nts-Win32-VC15-x64\php.exe

**Comment by Creexy** [comment]
+new error:

 [Composer\Downloader\TransportException]                                                                   
  The "http://packagist.org/p/symfony/polyfill-mbstring%24acf8410c8db5832789a01cc3c07ed937432e6a5            59891910a3f0d1d01ac8
  3c978.json" file could not be downloaded: failed to open stream: HTTP request failed!

**Comment by Creexy** [comment]
just needed to turn off the antivirus
