### ISSUE TITLE
<unknown> when on Charles Proxy api-quiz.hype.space

### ISSUE THREAD

**Issue by nolanplatt** [mikealmond/hq-trivia-assistant#71]
Hello,

when I am on Charles Proxy and on api-quiz.hype.space, I get this:

![screen shot 2018-02-16 at 6 39 31 pm](https://user-images.githubusercontent.com/20466654/36337332-c1d0da5c-1348-11e8-8c42-4991bb64b1a1.png)

Anyone know how to fix this?
Thanks

**Comment by nolanplatt** [comment]
Also on HQ it says "Error loading schedule"

**Comment by nolanplatt** [comment]
Figured it out by looking at #5. Closed

**Comment by sixthhokage4** [comment]
Can someone please help ? I am facing the same problem and i have visited [#5](https://github.com/mikealmond/hq-trivia-assistant/issues/5) but there is no solution to it. _When I enable SSL proxying_, the <unknown> appears and _when I disable SSL proxying_, the content on right side is all gibberish.

**Comment by sixthhokage4** [comment]
<img width="468" alt="ch" src="https://user-images.githubusercontent.com/36645562/36396544-c4fe3eba-15e4-11e8-9135-192b9d54239c.png">

**Comment by tombets2424** [comment]
Go to #59

**Comment by nolanplatt** [comment]
Hi @sixthhokage4 ,
you need to enable full root access in settings general about cert. trust settings.

Cheers!
