### ISSUE TITLE
Could not open input file: run.php

### ISSUE THREAD

**Issue by kandyceasania101** [mikealmond/hq-trivia-assistant#74]
After I have entered my token bearer and my user id I type "php run.php" and get the above error.  I am using the windows command prompt. Everything went smoothly up until now. Could there be an issue with running this php script on windows?

**Comment by tombets2424** [comment]
Do you have php installed? 
You should also use GitBash to run this program. When you have it installed right click in the hq-trivia-assistant folder and click run GitBash. See if these fix it. If not can you show what error you get by printscreen.

**Comment by kandyceasania101** [comment]
I installed php using xampp. I ran "php -v" and it says I am using version 7.2.2. After running the script in GitBash I get a new error:
`PHP Warning:  require(C:\Users\KandyceAsania\hq-trivia-assistant/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\KandyceAsania\hq-trivia-assistant\run.php on line 9

Warning: require(C:\Users\KandyceAsania\hq-trivia-assistant/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\KandyceAsania\hq-trivia-assistant\run.php on line 9
PHP Fatal error:  require(): Failed opening required 'C:\Users\KandyceAsania\hq-trivia-assistant/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\KandyceAsania\hq-trivia-assistant\run.php on line 9

Fatal error: require(): Failed opening required 'C:\Users\KandyceAsania\hq-trivia-assistant/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\KandyceAsania\hq-trivia-assistant\run.php on line 9`

Does this have something to do with the include_path ??

**Comment by kandyceasania101** [comment]
UPDATE: Got it to work! I had to reinstall composer again within GitBash in order for it to work. I had already installed it but I guess it needs to be installed within each folder I plan to run php..

Thank You!

**Comment by kandyceasania101** [comment]
Out of curiosity, have you attempted to create a similar tool that works with Cash Show as well?  It is an application pretty similar to HQ.

**Comment by tombets2424** [comment]
No, I also haven't seen a cash show bot yet. I have done some digging of my own though and it probably could be done, if someone knew what they were doing. It doesn't show you the user ID  but dose show you something similar to a BEARER TOKEN. it could be done though.
