### ISSUE TITLE
Full Video Tutorial

### ISSUE THREAD

**Issue by nolanplatt** [mikealmond/hq-trivia-assistant#81]
Hello!
I am selling a full video tutorial on how to set this up. I will include unlimited help and if their are errors I will figure them out.

Payment: we can work out payment on discord. Add me: nolan#4288

Also full writing tutorial included .

Cheers!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by savageduckerino** [comment]
1. open gitbash
2. paste in the included code in readme.md
3. don't pay for something thats easy to do
