### ISSUE TITLE
Error loading schedule

### ISSUE THREAD

**Issue by nolanplatt** [mikealmond/hq-trivia-assistant#84]
Whenever I am on my wifi connection my wifi is super slow and can't load HQ... any fix? This results in bot not working because I have to play HQ on cellular. Need fix ASAP, thanks.

**Comment by nolanplatt** [comment]
This is what happens: 
![image](https://user-images.githubusercontent.com/20466654/36445258-9393e480-1632-11e8-9591-87f1374feeb0.png)

**Comment by Monogol** [comment]
And it only gets slow when you run the hq bot?

**Comment by nolanplatt** [comment]
No, all the time.

**Comment by Monogol** [comment]
maybe try tethering internet from your phone to your computer

**Comment by nolanplatt** [comment]
Fixed, closed.
