### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by savageduckerino** [mikealmond/hq-trivia-assistant#88]
I have everything downloaded, yet I don't know how to use the composer because it asks me to select a php.exe I don't have.
This is what I get when i run it in git bash: http://prntscr.com/iil4bw

**Comment by savageduckerino** [comment]
Ok I think i've installed it, but how do i run it?

**Comment by savageduckerino** [comment]
ok, I think i finally installed it but it says error: auth not valid errorCode: 105
is it because the show isnt live?

**Comment by Monogol** [comment]
#82

**Comment by savageduckerino** [comment]
well I mean i Installed it just how do i run it

**Comment by savageduckerino** [comment]
http://prntscr.com/iizgcm
this is what it says
