### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by D-Buz** [mikealmond/hq-trivia-assistant#9]
No file is created after typing in "cp .env.dist .env" after the rest of the steps... I have composer installed.

**Comment by robertsmith7** [comment]
"cp .env.dist .env should not display anything in terminal, as it just copies a file. After you copy it you can do nano .env or vi .env to edit the file and add your bearer and user ID." @D-Buz

**Comment by frankbeirne** [comment]
@D-Buz If you're trying to view the file in finder, you may not have hidden files showing. If you're in Mac you could run `defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app`

**Comment by D-Buz** [comment]
@frankbeirne That did the trick thanks
